baseURL = "https://hypno.cat"
languageCode = "fr"
title = "hypno.cat"
theme = "hypno.cat"
defaultContentLanguage = 'fr'


[languages]
  [languages.fr]
    weight = 1
    languageName = 'Français'
    contentDir = 'content/fr'
