baseURL = "https://hypno.cat"
languageCode = "en-us"
title = "hypno.cat"
theme = "hypno.cat"
defaultContentLanguage = "fr"

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    weight = 1
  [languages.cat]
    contentDir = 'content/cat'
    languageName = 'Català'
    weight = 2

[permalinks]
	posts = "/posts/:year-:month-:day/:slug"