baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hypno.cat"
defaultContentLanguage = "fr"

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    weight = 1
  [languages.cat]
    contentDir = 'content/cat'
    languageName = 'Català'
    weight = 2
