name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@771cd2231a
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
